#!/bin/bash
if [ `id -u` -ne 0 ]
then
    echo "Need to be ROOT."
    exit 1
fi

./zdclient -u username -p password -d 202.96.128.1 -g 172.18.18.254 -b

#若使用DHCP，把以下四行的#去掉
#if [ $? -eq 0 ]
#then
#	dhclient
#fi

exit 0
